### ISSUE TITLE
Allow analysis of raw file content

### ISSUE THREAD

**Issue by Nixinova** [Nixinova/Linguist#10]
### **Discussed in https://github.com/Nixinova/Linguist/discussions/9** &rarr;

<div type='discussions-op-text'>

<sup>Originally posted by **lowlighter** February  8, 2022</sup>

From what I understand, the exported `analyse` function only takes a list of paths as inputs, and from there it'll walk on each file in given directories:
https://github.com/Nixinova/Linguist/blob/9a15a06266b45a0075351c8884a519d42cc252b0/src/index.ts#L16-L18

Would it be possible to expose another entry point which directly accepts a raw string as argument and returns the result instead ?
</div>

<hr>

This requires a refactoring of all the `index.ts` source as each stage in the analysis would need to be able to be called separately.

The function header would be something like this:
```ts
interface Metadata { filename: string, /* extension: string //? */, size: number, /* ... */ };
export default async function analyseSingle(content: string | string[], metadata: Metadata, opts?: T.Options): Promise<T.Results> {
```

**Comment by Nixinova** [comment]
This shouldn't need a rewrite actually, it can be done without having to move too much about
see https://github.com/Nixinova/Linguist/commit/1878abfa665bd9e25ab2989533c51bfe2c77617c
Will add this change for 2.3.

**Comment by princefishthrower** [comment]
@Nixinova - so, as far as I can tell, this is not yet in the codebase! Has the API changed for raw input or is there a more updated example?

**Comment by Nixinova** [comment]
See https://github.com/Nixinova/LinguistJS/issues/30#issuecomment-1985362112 :+1:
