### ISSUE TITLE
A few files are missing after upgrading from 2.0.0 to 2.0.2

### ISSUE THREAD

**Issue by kachkaev** [Nixinova/Linguist#7]
👋 I’ve noticed a small but strange change after upgrading linguist, it's possibly to do with 6c33a85ef1dd838a788efcd431ecdae01407907a.

These files are missing in my updated linguist report:

```json
{
    ".gitattributes": "Git Attributes",
    ".gitignore": "Ignore List",
    ".vscode/extensions.json": "JSON",
    ".vscode/launch.json": "JSON",
    ".vscode/settings.json": "JSON",
    "no/matter/what/path/declaration.d.ts": "TypeScript",
}
```

Just curious if this is a wanted change or not, so have decided to check this via an issue 🙂

**Comment by Nixinova** [comment]
All of those are classified as vendored:
- Git config files: https://github.com/github/linguist/blob/4fc6808d99980a88465861217db6b74cd0d639d3/lib/linguist/vendor.yml#L287-L290
- vscode: https://github.com/github/linguist/blob/4fc6808d99980a88465861217db6b74cd0d639d3/lib/linguist/vendor.yml#L171
- d.ts: https://github.com/github/linguist/blob/4fc6808d99980a88465861217db6b74cd0d639d3/lib/linguist/vendor.yml#L180

**Comment by kachkaev** [comment]
IC, so it’s a bugfix rather than a regression. Makes sense, thanks for explaining! 👍
